
from abmax.structs import *
from abmax.functions import *
import jax.numpy as jnp
import jax.random as random
import jax
from flax import struct
from sim_params import *

@struct.dataclass
class Point:
    x: jnp.float32
    y: jnp.float32

@struct.dataclass
class Line:
    p1: Point
    p2: Point

@struct.dataclass
class Circle:
    center: Point
    radius: jnp.float32

@struct.dataclass
class Ray:
    origin: Point
    direction: Point # cos, sin
    length: jnp.float32


def generate_rays(agent_pos:Agent, ray_span:jnp.float32, ray_length:jnp.float32):
    """
    Generate rays for the agent given the agent position, the span of the rays, the length of the rays and the number of rays
    Args:
        - agent_pos: The position of the agent: (x, y, angle)
        - ray_span: The span of the rays i.e. how wide the agent can see by 2
        - ray_length: The length of the rays
        - RAY_RESOLUTION: The number of rays is global
    Returns:
        The rays generated by the agent at the given position
    """
    x, y, angle = agent_pos

    ray_angles = jnp.linspace(angle - ray_span, angle + ray_span, RAY_RESOLUTION, endpoint=False) # endpoint false to avoid overlapping rays when span = pi
    cos_ray_angles = jnp.cos(ray_angles)
    sin_ray_angles = jnp.sin(ray_angles)
    ray_directions = jax.vmap(Point)(cos_ray_angles, sin_ray_angles)
    
    ray_origin = Point(x, y)
    
    rays = jax.vmap(Ray, in_axes=(None, 0, None))(ray_origin, ray_directions, ray_length)
    return rays

jit_generate_rays = jax.jit(generate_rays)


def get_ray_circle_collision(ray:Ray, circle:Circle):
    """
    ray casting algorithm to check for collision between a ray and a circle, adapted from https://www.youtube.com/watch?v=ebzlMOw79Yw&ab_channel=MagellanicMath
    Args:
        - ray: Ray, The ray to check for collision
        - circle: Circle, The circle to check for collision
    Returns:
        The distance of the collision of the ray with the circle along the ray
    """
    circle_center = jnp.reshape(jnp.array([circle.center.x, circle.center.y]), (2,))
    ray_origin = jnp.reshape(jnp.array([ray.origin.x, ray.origin.y]), (2,))
    ray_direction = jnp.reshape(jnp.array([ray.direction.x, ray.direction.y]), (2,))

    s = ray_origin - circle_center
    b = jnp.dot(s, ray_direction)
    c = jnp.dot(s, s) - circle.radius**2
    h = b**2 - c
    h = jax.lax.cond(h < 0, lambda _: -1.0, lambda _: jnp.sqrt(h), None)
    t = jax.lax.cond(h >= 0, lambda _: -b - h, lambda _: ray.length, None)
    t = jax.lax.cond(t < 0, lambda _: ray.length, lambda _: t, None) # this enables the agent to see ouside the circle
    return jnp.minimum(t, ray.length)

jit_get_ray_circle_collision = jax.jit(get_ray_circle_collision)